// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0--rc3
// source: feed-api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LikeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdFrom int32 `protobuf:"varint,1,opt,name=IdFrom,proto3" json:"IdFrom,omitempty"`
	IdTo   int32 `protobuf:"varint,2,opt,name=IdTo,proto3" json:"IdTo,omitempty"`
}

func (x *LikeRequest) Reset() {
	*x = LikeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeRequest) ProtoMessage() {}

func (x *LikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeRequest.ProtoReflect.Descriptor instead.
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{0}
}

func (x *LikeRequest) GetIdFrom() int32 {
	if x != nil {
		return x.IdFrom
	}
	return 0
}

func (x *LikeRequest) GetIdTo() int32 {
	if x != nil {
		return x.IdTo
	}
	return 0
}

type LikeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Done       bool `protobuf:"varint,1,opt,name=Done,proto3" json:"Done,omitempty"`
	Match      bool `protobuf:"varint,2,opt,name=Match,proto3" json:"Match,omitempty"`
	OutOfLikes bool `protobuf:"varint,3,opt,name=OutOfLikes,proto3" json:"OutOfLikes,omitempty"`
}

func (x *LikeResponse) Reset() {
	*x = LikeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeResponse) ProtoMessage() {}

func (x *LikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeResponse.ProtoReflect.Descriptor instead.
func (*LikeResponse) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{1}
}

func (x *LikeResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *LikeResponse) GetMatch() bool {
	if x != nil {
		return x.Match
	}
	return false
}

func (x *LikeResponse) GetOutOfLikes() bool {
	if x != nil {
		return x.OutOfLikes
	}
	return false
}

type SuperLikeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdFrom  int32  `protobuf:"varint,1,opt,name=IdFrom,proto3" json:"IdFrom,omitempty"`
	IdTo    int32  `protobuf:"varint,2,opt,name=IdTo,proto3" json:"IdTo,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *SuperLikeRequest) Reset() {
	*x = SuperLikeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuperLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuperLikeRequest) ProtoMessage() {}

func (x *SuperLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuperLikeRequest.ProtoReflect.Descriptor instead.
func (*SuperLikeRequest) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{2}
}

func (x *SuperLikeRequest) GetIdFrom() int32 {
	if x != nil {
		return x.IdFrom
	}
	return 0
}

func (x *SuperLikeRequest) GetIdTo() int32 {
	if x != nil {
		return x.IdTo
	}
	return 0
}

func (x *SuperLikeRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SuperLikeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Done  bool `protobuf:"varint,1,opt,name=Done,proto3" json:"Done,omitempty"`
	Match bool `protobuf:"varint,2,opt,name=Match,proto3" json:"Match,omitempty"`
}

func (x *SuperLikeResponse) Reset() {
	*x = SuperLikeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuperLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuperLikeResponse) ProtoMessage() {}

func (x *SuperLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuperLikeResponse.ProtoReflect.Descriptor instead.
func (*SuperLikeResponse) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{3}
}

func (x *SuperLikeResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *SuperLikeResponse) GetMatch() bool {
	if x != nil {
		return x.Match
	}
	return false
}

type DislikeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdFrom int32 `protobuf:"varint,1,opt,name=IdFrom,proto3" json:"IdFrom,omitempty"`
	IdTo   int32 `protobuf:"varint,2,opt,name=IdTo,proto3" json:"IdTo,omitempty"`
}

func (x *DislikeRequest) Reset() {
	*x = DislikeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DislikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DislikeRequest) ProtoMessage() {}

func (x *DislikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DislikeRequest.ProtoReflect.Descriptor instead.
func (*DislikeRequest) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{4}
}

func (x *DislikeRequest) GetIdFrom() int32 {
	if x != nil {
		return x.IdFrom
	}
	return 0
}

func (x *DislikeRequest) GetIdTo() int32 {
	if x != nil {
		return x.IdTo
	}
	return 0
}

type DislikeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Done bool `protobuf:"varint,1,opt,name=Done,proto3" json:"Done,omitempty"`
}

func (x *DislikeResponse) Reset() {
	*x = DislikeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DislikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DislikeResponse) ProtoMessage() {}

func (x *DislikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DislikeResponse.ProtoReflect.Descriptor instead.
func (*DislikeResponse) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{5}
}

func (x *DislikeResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type SaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdFrom int32 `protobuf:"varint,1,opt,name=IdFrom,proto3" json:"IdFrom,omitempty"`
	IdTo   int32 `protobuf:"varint,2,opt,name=IdTo,proto3" json:"IdTo,omitempty"`
}

func (x *SaveRequest) Reset() {
	*x = SaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequest) ProtoMessage() {}

func (x *SaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRequest.ProtoReflect.Descriptor instead.
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{6}
}

func (x *SaveRequest) GetIdFrom() int32 {
	if x != nil {
		return x.IdFrom
	}
	return 0
}

func (x *SaveRequest) GetIdTo() int32 {
	if x != nil {
		return x.IdTo
	}
	return 0
}

type SaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Done bool `protobuf:"varint,2,opt,name=Done,proto3" json:"Done,omitempty"`
}

func (x *SaveResponse) Reset() {
	*x = SaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResponse) ProtoMessage() {}

func (x *SaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResponse.ProtoReflect.Descriptor instead.
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{7}
}

func (x *SaveResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type WhoLikedMeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *WhoLikedMeRequest) Reset() {
	*x = WhoLikedMeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhoLikedMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoLikedMeRequest) ProtoMessage() {}

func (x *WhoLikedMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoLikedMeRequest.ProtoReflect.Descriptor instead.
func (*WhoLikedMeRequest) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{8}
}

func (x *WhoLikedMeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type WhoLikedMeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []int32 `protobuf:"varint,1,rep,packed,name=Users,proto3" json:"Users,omitempty"`
}

func (x *WhoLikedMeResponse) Reset() {
	*x = WhoLikedMeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhoLikedMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoLikedMeResponse) ProtoMessage() {}

func (x *WhoLikedMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoLikedMeResponse.ProtoReflect.Descriptor instead.
func (*WhoLikedMeResponse) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{9}
}

func (x *WhoLikedMeResponse) GetUsers() []int32 {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetSavedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *GetSavedRequest) Reset() {
	*x = GetSavedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSavedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSavedRequest) ProtoMessage() {}

func (x *GetSavedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSavedRequest.ProtoReflect.Descriptor instead.
func (*GetSavedRequest) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{10}
}

func (x *GetSavedRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSavedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []int32 `protobuf:"varint,1,rep,packed,name=Users,proto3" json:"Users,omitempty"`
}

func (x *GetSavedResponse) Reset() {
	*x = GetSavedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSavedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSavedResponse) ProtoMessage() {}

func (x *GetSavedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSavedResponse.ProtoReflect.Descriptor instead.
func (*GetSavedResponse) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{11}
}

func (x *GetSavedResponse) GetUsers() []int32 {
	if x != nil {
		return x.Users
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{12}
}

type CreateUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Done bool `protobuf:"varint,1,opt,name=Done,proto3" json:"Done,omitempty"`
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{13}
}

func (x *CreateUserResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Done bool `protobuf:"varint,1,opt,name=Done,proto3" json:"Done,omitempty"`
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteUserResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_feed_api_proto protoreflect.FileDescriptor

var file_feed_api_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x66, 0x65, 0x65, 0x64, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x2e, 0x76, 0x31, 0x22, 0x39,
	0x0a, 0x0b, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x49, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x49,
	0x64, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x64, 0x54, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x49, 0x64, 0x54, 0x6f, 0x22, 0x58, 0x0a, 0x0c, 0x4c, 0x69, 0x6b,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x6f, 0x6e,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x44, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x4f, 0x75, 0x74, 0x4f, 0x66, 0x4c, 0x69, 0x6b, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x4f, 0x75, 0x74, 0x4f, 0x66, 0x4c, 0x69,
	0x6b, 0x65, 0x73, 0x22, 0x58, 0x0a, 0x10, 0x53, 0x75, 0x70, 0x65, 0x72, 0x4c, 0x69, 0x6b, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x64, 0x46, 0x72, 0x6f,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x49, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x12,
	0x12, 0x0a, 0x04, 0x49, 0x64, 0x54, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x49,
	0x64, 0x54, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3d, 0x0a,
	0x11, 0x53, 0x75, 0x70, 0x65, 0x72, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x44, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x22, 0x3c, 0x0a, 0x0e,
	0x44, 0x69, 0x73, 0x6c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x49, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x49, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x64, 0x54, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x49, 0x64, 0x54, 0x6f, 0x22, 0x25, 0x0a, 0x0f, 0x44, 0x69,
	0x73, 0x6c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x44, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x44, 0x6f, 0x6e,
	0x65, 0x22, 0x39, 0x0a, 0x0b, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x49, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x49, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x64, 0x54, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x49, 0x64, 0x54, 0x6f, 0x22, 0x22, 0x0a, 0x0c,
	0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x44, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x44, 0x6f, 0x6e, 0x65,
	0x22, 0x23, 0x0a, 0x11, 0x57, 0x68, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x4d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x49, 0x64, 0x22, 0x2a, 0x0a, 0x12, 0x57, 0x68, 0x6f, 0x4c, 0x69, 0x6b, 0x65,
	0x64, 0x4d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x61, 0x76, 0x65, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x49, 0x64, 0x22, 0x28, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x61, 0x76, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x55, 0x73, 0x65, 0x72, 0x73, 0x22, 0x13,
	0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x28, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x6f, 0x6e,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x44, 0x6f, 0x6e, 0x65, 0x22, 0x23, 0x0a,
	0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x49, 0x64, 0x22, 0x28, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x6f, 0x6e, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x44, 0x6f, 0x6e, 0x65, 0x32, 0xdc, 0x04, 0x0a,
	0x08, 0x46, 0x65, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x12, 0x3d, 0x0a, 0x04, 0x4c, 0x69, 0x6b,
	0x65, 0x12, 0x19, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x66,
	0x65, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x6b, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x09, 0x53, 0x75, 0x70, 0x65,
	0x72, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x1e, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x70, 0x65, 0x72, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x70, 0x65, 0x72, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x07, 0x44, 0x69, 0x73, 0x6c, 0x69, 0x6b,
	0x65, 0x12, 0x1c, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x69, 0x73, 0x6c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x69, 0x73, 0x6c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d,
	0x0a, 0x04, 0x53, 0x61, 0x76, 0x65, 0x12, 0x19, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a,
	0x0a, 0x57, 0x68, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x4d, 0x65, 0x12, 0x1f, 0x2e, 0x66, 0x65,
	0x65, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x68, 0x6f, 0x4c, 0x69,
	0x6b, 0x65, 0x64, 0x4d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x66,
	0x65, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x68, 0x6f, 0x4c,
	0x69, 0x6b, 0x65, 0x64, 0x4d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x61, 0x76, 0x65, 0x64, 0x12, 0x1d, 0x2e, 0x66, 0x65, 0x65,
	0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x61, 0x76,
	0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x66, 0x65, 0x65, 0x64,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x61, 0x76, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0a, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x66, 0x65, 0x65, 0x64,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2b, 0x5a, 0x29, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6e, 0x73, 0x70, 0x33, 0x63,
	0x74, 0x61, 0x68, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_feed_api_proto_rawDescOnce sync.Once
	file_feed_api_proto_rawDescData = file_feed_api_proto_rawDesc
)

func file_feed_api_proto_rawDescGZIP() []byte {
	file_feed_api_proto_rawDescOnce.Do(func() {
		file_feed_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_feed_api_proto_rawDescData)
	})
	return file_feed_api_proto_rawDescData
}

var file_feed_api_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_feed_api_proto_goTypes = []interface{}{
	(*LikeRequest)(nil),        // 0: feed_serv.v1.LikeRequest
	(*LikeResponse)(nil),       // 1: feed_serv.v1.LikeResponse
	(*SuperLikeRequest)(nil),   // 2: feed_serv.v1.SuperLikeRequest
	(*SuperLikeResponse)(nil),  // 3: feed_serv.v1.SuperLikeResponse
	(*DislikeRequest)(nil),     // 4: feed_serv.v1.DislikeRequest
	(*DislikeResponse)(nil),    // 5: feed_serv.v1.DislikeResponse
	(*SaveRequest)(nil),        // 6: feed_serv.v1.SaveRequest
	(*SaveResponse)(nil),       // 7: feed_serv.v1.SaveResponse
	(*WhoLikedMeRequest)(nil),  // 8: feed_serv.v1.WhoLikedMeRequest
	(*WhoLikedMeResponse)(nil), // 9: feed_serv.v1.WhoLikedMeResponse
	(*GetSavedRequest)(nil),    // 10: feed_serv.v1.GetSavedRequest
	(*GetSavedResponse)(nil),   // 11: feed_serv.v1.GetSavedResponse
	(*CreateUserRequest)(nil),  // 12: feed_serv.v1.CreateUserRequest
	(*CreateUserResponse)(nil), // 13: feed_serv.v1.CreateUserResponse
	(*DeleteUserRequest)(nil),  // 14: feed_serv.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil), // 15: feed_serv.v1.DeleteUserResponse
}
var file_feed_api_proto_depIdxs = []int32{
	0,  // 0: feed_serv.v1.FeedServ.Like:input_type -> feed_serv.v1.LikeRequest
	2,  // 1: feed_serv.v1.FeedServ.SuperLike:input_type -> feed_serv.v1.SuperLikeRequest
	4,  // 2: feed_serv.v1.FeedServ.Dislike:input_type -> feed_serv.v1.DislikeRequest
	6,  // 3: feed_serv.v1.FeedServ.Save:input_type -> feed_serv.v1.SaveRequest
	8,  // 4: feed_serv.v1.FeedServ.WhoLikedMe:input_type -> feed_serv.v1.WhoLikedMeRequest
	10, // 5: feed_serv.v1.FeedServ.GetSaved:input_type -> feed_serv.v1.GetSavedRequest
	12, // 6: feed_serv.v1.FeedServ.CreateUser:input_type -> feed_serv.v1.CreateUserRequest
	14, // 7: feed_serv.v1.FeedServ.DeleteUser:input_type -> feed_serv.v1.DeleteUserRequest
	1,  // 8: feed_serv.v1.FeedServ.Like:output_type -> feed_serv.v1.LikeResponse
	3,  // 9: feed_serv.v1.FeedServ.SuperLike:output_type -> feed_serv.v1.SuperLikeResponse
	5,  // 10: feed_serv.v1.FeedServ.Dislike:output_type -> feed_serv.v1.DislikeResponse
	7,  // 11: feed_serv.v1.FeedServ.Save:output_type -> feed_serv.v1.SaveResponse
	9,  // 12: feed_serv.v1.FeedServ.WhoLikedMe:output_type -> feed_serv.v1.WhoLikedMeResponse
	11, // 13: feed_serv.v1.FeedServ.GetSaved:output_type -> feed_serv.v1.GetSavedResponse
	13, // 14: feed_serv.v1.FeedServ.CreateUser:output_type -> feed_serv.v1.CreateUserResponse
	15, // 15: feed_serv.v1.FeedServ.DeleteUser:output_type -> feed_serv.v1.DeleteUserResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_feed_api_proto_init() }
func file_feed_api_proto_init() {
	if File_feed_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_feed_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuperLikeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuperLikeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DislikeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DislikeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhoLikedMeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhoLikedMeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSavedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSavedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_feed_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feed_api_proto_goTypes,
		DependencyIndexes: file_feed_api_proto_depIdxs,
		MessageInfos:      file_feed_api_proto_msgTypes,
	}.Build()
	File_feed_api_proto = out.File
	file_feed_api_proto_rawDesc = nil
	file_feed_api_proto_goTypes = nil
	file_feed_api_proto_depIdxs = nil
}
