// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: feed-api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LikeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	Id          int32  `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *LikeRequest) Reset() {
	*x = LikeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeRequest) ProtoMessage() {}

func (x *LikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeRequest.ProtoReflect.Descriptor instead.
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{0}
}

func (x *LikeRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LikeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LikeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Done       bool `protobuf:"varint,1,opt,name=Done,proto3" json:"Done,omitempty"`
	Match      bool `protobuf:"varint,2,opt,name=Match,proto3" json:"Match,omitempty"`
	OutOfLikes bool `protobuf:"varint,3,opt,name=OutOfLikes,proto3" json:"OutOfLikes,omitempty"`
}

func (x *LikeResponse) Reset() {
	*x = LikeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeResponse) ProtoMessage() {}

func (x *LikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeResponse.ProtoReflect.Descriptor instead.
func (*LikeResponse) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{1}
}

func (x *LikeResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *LikeResponse) GetMatch() bool {
	if x != nil {
		return x.Match
	}
	return false
}

func (x *LikeResponse) GetOutOfLikes() bool {
	if x != nil {
		return x.OutOfLikes
	}
	return false
}

type SuperLikeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	Id          int32  `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Message     string `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *SuperLikeRequest) Reset() {
	*x = SuperLikeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuperLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuperLikeRequest) ProtoMessage() {}

func (x *SuperLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuperLikeRequest.ProtoReflect.Descriptor instead.
func (*SuperLikeRequest) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{2}
}

func (x *SuperLikeRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SuperLikeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SuperLikeRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SuperLikeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Done  bool `protobuf:"varint,1,opt,name=Done,proto3" json:"Done,omitempty"`
	Match bool `protobuf:"varint,2,opt,name=Match,proto3" json:"Match,omitempty"`
}

func (x *SuperLikeResponse) Reset() {
	*x = SuperLikeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuperLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuperLikeResponse) ProtoMessage() {}

func (x *SuperLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuperLikeResponse.ProtoReflect.Descriptor instead.
func (*SuperLikeResponse) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{3}
}

func (x *SuperLikeResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *SuperLikeResponse) GetMatch() bool {
	if x != nil {
		return x.Match
	}
	return false
}

type DislikeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	Id          int32  `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *DislikeRequest) Reset() {
	*x = DislikeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DislikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DislikeRequest) ProtoMessage() {}

func (x *DislikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DislikeRequest.ProtoReflect.Descriptor instead.
func (*DislikeRequest) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{4}
}

func (x *DislikeRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *DislikeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DislikeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Done bool `protobuf:"varint,1,opt,name=Done,proto3" json:"Done,omitempty"`
}

func (x *DislikeResponse) Reset() {
	*x = DislikeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DislikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DislikeResponse) ProtoMessage() {}

func (x *DislikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DislikeResponse.ProtoReflect.Descriptor instead.
func (*DislikeResponse) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{5}
}

func (x *DislikeResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type SaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	Id          int32  `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *SaveRequest) Reset() {
	*x = SaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequest) ProtoMessage() {}

func (x *SaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRequest.ProtoReflect.Descriptor instead.
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{6}
}

func (x *SaveRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SaveRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Done bool `protobuf:"varint,2,opt,name=Done,proto3" json:"Done,omitempty"`
}

func (x *SaveResponse) Reset() {
	*x = SaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResponse) ProtoMessage() {}

func (x *SaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResponse.ProtoReflect.Descriptor instead.
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return file_feed_api_proto_rawDescGZIP(), []int{7}
}

func (x *SaveResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_feed_api_proto protoreflect.FileDescriptor

var file_feed_api_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x66, 0x65, 0x65, 0x64, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x22, 0x3f, 0x0a,
	0x0b, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x22, 0x58,
	0x0a, 0x0c, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x44, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x44, 0x6f,
	0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x4f, 0x75, 0x74, 0x4f,
	0x66, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x4f, 0x75,
	0x74, 0x4f, 0x66, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x22, 0x5e, 0x0a, 0x10, 0x53, 0x75, 0x70, 0x65,
	0x72, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3d, 0x0a, 0x11, 0x53, 0x75, 0x70, 0x65,
	0x72, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x44, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x44, 0x6f, 0x6e,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x22, 0x42, 0x0a, 0x0e, 0x44, 0x69, 0x73, 0x6c, 0x69,
	0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x22, 0x25, 0x0a, 0x0f, 0x44,
	0x69, 0x73, 0x6c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x44, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x44, 0x6f,
	0x6e, 0x65, 0x22, 0x3f, 0x0a, 0x0b, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x49, 0x64, 0x22, 0x22, 0x0a, 0x0c, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x44, 0x6f, 0x6e, 0x65, 0x32, 0x92, 0x02, 0x0a, 0x04, 0x46, 0x65, 0x65, 0x64,
	0x12, 0x3b, 0x0a, 0x04, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x18, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a,
	0x09, 0x53, 0x75, 0x70, 0x65, 0x72, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x1d, 0x2e, 0x66, 0x65, 0x65,
	0x64, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x70, 0x65, 0x72, 0x4c, 0x69,
	0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x66, 0x65, 0x65, 0x64,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x70, 0x65, 0x72, 0x4c, 0x69, 0x6b,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x07, 0x44, 0x69, 0x73,
	0x6c, 0x69, 0x6b, 0x65, 0x12, 0x1b, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x6c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x69, 0x73, 0x6c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3b, 0x0a, 0x04, 0x53, 0x61, 0x76, 0x65, 0x12, 0x18, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2b, 0x5a, 0x29,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6e, 0x73, 0x70, 0x33,
	0x63, 0x74, 0x61, 0x68, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_feed_api_proto_rawDescOnce sync.Once
	file_feed_api_proto_rawDescData = file_feed_api_proto_rawDesc
)

func file_feed_api_proto_rawDescGZIP() []byte {
	file_feed_api_proto_rawDescOnce.Do(func() {
		file_feed_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_feed_api_proto_rawDescData)
	})
	return file_feed_api_proto_rawDescData
}

var file_feed_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_feed_api_proto_goTypes = []any{
	(*LikeRequest)(nil),       // 0: feed_api.v1.LikeRequest
	(*LikeResponse)(nil),      // 1: feed_api.v1.LikeResponse
	(*SuperLikeRequest)(nil),  // 2: feed_api.v1.SuperLikeRequest
	(*SuperLikeResponse)(nil), // 3: feed_api.v1.SuperLikeResponse
	(*DislikeRequest)(nil),    // 4: feed_api.v1.DislikeRequest
	(*DislikeResponse)(nil),   // 5: feed_api.v1.DislikeResponse
	(*SaveRequest)(nil),       // 6: feed_api.v1.SaveRequest
	(*SaveResponse)(nil),      // 7: feed_api.v1.SaveResponse
}
var file_feed_api_proto_depIdxs = []int32{
	0, // 0: feed_api.v1.Feed.Like:input_type -> feed_api.v1.LikeRequest
	2, // 1: feed_api.v1.Feed.SuperLike:input_type -> feed_api.v1.SuperLikeRequest
	4, // 2: feed_api.v1.Feed.Dislike:input_type -> feed_api.v1.DislikeRequest
	6, // 3: feed_api.v1.Feed.Save:input_type -> feed_api.v1.SaveRequest
	1, // 4: feed_api.v1.Feed.Like:output_type -> feed_api.v1.LikeResponse
	3, // 5: feed_api.v1.Feed.SuperLike:output_type -> feed_api.v1.SuperLikeResponse
	5, // 6: feed_api.v1.Feed.Dislike:output_type -> feed_api.v1.DislikeResponse
	7, // 7: feed_api.v1.Feed.Save:output_type -> feed_api.v1.SaveResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_feed_api_proto_init() }
func file_feed_api_proto_init() {
	if File_feed_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_feed_api_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*LikeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_api_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*LikeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_api_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SuperLikeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_api_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SuperLikeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_api_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DislikeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_api_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DislikeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_api_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*SaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_api_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*SaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_feed_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feed_api_proto_goTypes,
		DependencyIndexes: file_feed_api_proto_depIdxs,
		MessageInfos:      file_feed_api_proto_msgTypes,
	}.Build()
	File_feed_api_proto = out.File
	file_feed_api_proto_rawDesc = nil
	file_feed_api_proto_goTypes = nil
	file_feed_api_proto_depIdxs = nil
}
