// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: ai.proto

package ai_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WantedSex int32

const (
	WantedSex_DRAFT_STATUS_UNSPECIFIED WantedSex = 0
	WantedSex_WANTED_STATUS_MEN        WantedSex = 1
	WantedSex_WANTED_STATUS_WOMEN      WantedSex = 2
	WantedSex_WANTED_STATUS_NO_MATTER  WantedSex = 3
)

// Enum value maps for WantedSex.
var (
	WantedSex_name = map[int32]string{
		0: "DRAFT_STATUS_UNSPECIFIED",
		1: "WANTED_STATUS_MEN",
		2: "WANTED_STATUS_WOMEN",
		3: "WANTED_STATUS_NO_MATTER",
	}
	WantedSex_value = map[string]int32{
		"DRAFT_STATUS_UNSPECIFIED": 0,
		"WANTED_STATUS_MEN":        1,
		"WANTED_STATUS_WOMEN":      2,
		"WANTED_STATUS_NO_MATTER":  3,
	}
)

func (x WantedSex) Enum() *WantedSex {
	p := new(WantedSex)
	*p = x
	return p
}

func (x WantedSex) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WantedSex) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_proto_enumTypes[0].Descriptor()
}

func (WantedSex) Type() protoreflect.EnumType {
	return &file_ai_proto_enumTypes[0]
}

func (x WantedSex) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WantedSex.Descriptor instead.
func (WantedSex) EnumDescriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartAge    int32     `protobuf:"varint,1,opt,name=StartAge,proto3" json:"StartAge,omitempty"`
	EndAge      int32     `protobuf:"varint,2,opt,name=EndAge,proto3" json:"EndAge,omitempty"`
	SexWanted   WantedSex `protobuf:"varint,3,opt,name=SexWanted,proto3,enum=ai.v1.WantedSex" json:"SexWanted,omitempty"`
	Verified    bool      `protobuf:"varint,4,opt,name=Verified,proto3" json:"Verified,omitempty"`
	Tags        []string  `protobuf:"bytes,5,rep,name=Tags,proto3" json:"Tags,omitempty"`
	MaxDistance int32     `protobuf:"varint,6,opt,name=MaxDistance,proto3" json:"MaxDistance,omitempty"`
	MinHeight   int32     `protobuf:"varint,7,opt,name=MinHeight,proto3" json:"MinHeight,omitempty"`
	MaxHeight   int32     `protobuf:"varint,8,opt,name=MaxHeight,proto3" json:"MaxHeight,omitempty"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

func (x *Filter) GetStartAge() int32 {
	if x != nil {
		return x.StartAge
	}
	return 0
}

func (x *Filter) GetEndAge() int32 {
	if x != nil {
		return x.EndAge
	}
	return 0
}

func (x *Filter) GetSexWanted() WantedSex {
	if x != nil {
		return x.SexWanted
	}
	return WantedSex_DRAFT_STATUS_UNSPECIFIED
}

func (x *Filter) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *Filter) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Filter) GetMaxDistance() int32 {
	if x != nil {
		return x.MaxDistance
	}
	return 0
}

func (x *Filter) GetMinHeight() int32 {
	if x != nil {
		return x.MinHeight
	}
	return 0
}

func (x *Filter) GetMaxHeight() int32 {
	if x != nil {
		return x.MaxHeight
	}
	return 0
}

type AiApiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Filter *Filter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *AiApiRequest) Reset() {
	*x = AiApiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AiApiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiApiRequest) ProtoMessage() {}

func (x *AiApiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiApiRequest.ProtoReflect.Descriptor instead.
func (*AiApiRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

func (x *AiApiRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AiApiRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type AiApiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdArray []int32 `protobuf:"varint,1,rep,packed,name=id_array,json=idArray,proto3" json:"id_array,omitempty"`
}

func (x *AiApiResponse) Reset() {
	*x = AiApiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AiApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiApiResponse) ProtoMessage() {}

func (x *AiApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiApiResponse.ProtoReflect.Descriptor instead.
func (*AiApiResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{2}
}

func (x *AiApiResponse) GetIdArray() []int32 {
	if x != nil {
		return x.IdArray
	}
	return nil
}

var File_ai_proto protoreflect.FileDescriptor

var file_ai_proto_rawDesc = []byte{
	0x0a, 0x08, 0x61, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x69, 0x2e, 0x76,
	0x31, 0x22, 0xfa, 0x01, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x6e, 0x64, 0x41,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x45, 0x6e, 0x64, 0x41, 0x67, 0x65,
	0x12, 0x2e, 0x0a, 0x09, 0x53, 0x65, 0x78, 0x57, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x61, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x6e, 0x74,
	0x65, 0x64, 0x53, 0x65, 0x78, 0x52, 0x09, 0x53, 0x65, 0x78, 0x57, 0x61, 0x6e, 0x74, 0x65, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x54, 0x61, 0x67, 0x73,
	0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x61, 0x78, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x4d, 0x61, 0x78, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x69, 0x6e, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x4d, 0x69, 0x6e, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x78, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x4d, 0x61, 0x78, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x45,
	0x0a, 0x0c, 0x41, 0x69, 0x41, 0x70, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25,
	0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x61, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x2a, 0x0a, 0x0d, 0x41, 0x69, 0x41, 0x70, 0x69, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x64, 0x5f, 0x61, 0x72, 0x72,
	0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x69, 0x64, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x2a, 0x76, 0x0a, 0x09, 0x57, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x53, 0x65, 0x78, 0x12, 0x1c,
	0x0a, 0x18, 0x44, 0x52, 0x41, 0x46, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11,
	0x57, 0x41, 0x4e, 0x54, 0x45, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4d, 0x45,
	0x4e, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x57, 0x41, 0x4e, 0x54, 0x45, 0x44, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x57, 0x4f, 0x4d, 0x45, 0x4e, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17,
	0x57, 0x41, 0x4e, 0x54, 0x45, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4e, 0x4f,
	0x5f, 0x4d, 0x41, 0x54, 0x54, 0x45, 0x52, 0x10, 0x03, 0x32, 0x48, 0x0a, 0x0c, 0x41, 0x69, 0x41,
	0x70, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x49, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x69, 0x12, 0x13, 0x2e, 0x61, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x69, 0x41, 0x70, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x61, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x69, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x45, 0x5a, 0x43, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x43, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x6f, 0x6e, 0x73,
	0x54, 0x65, 0x61, 0x6d, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x73, 0x2f, 0x62, 0x6c, 0x6f, 0x62, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x69, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData = file_ai_proto_rawDesc
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(file_ai_proto_rawDescData)
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ai_proto_goTypes = []any{
	(WantedSex)(0),        // 0: ai.v1.WantedSex
	(*Filter)(nil),        // 1: ai.v1.Filter
	(*AiApiRequest)(nil),  // 2: ai.v1.AiApiRequest
	(*AiApiResponse)(nil), // 3: ai.v1.AiApiResponse
}
var file_ai_proto_depIdxs = []int32{
	0, // 0: ai.v1.Filter.SexWanted:type_name -> ai.v1.WantedSex
	1, // 1: ai.v1.AiApiRequest.filter:type_name -> ai.v1.Filter
	2, // 2: ai.v1.AiApiService.GetIdFromAi:input_type -> ai.v1.AiApiRequest
	3, // 3: ai.v1.AiApiService.GetIdFromAi:output_type -> ai.v1.AiApiResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ai_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AiApiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AiApiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ai_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		EnumInfos:         file_ai_proto_enumTypes,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_rawDesc = nil
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
